"""Shared safety and support phone numbers."""

from __future__ import annotations

SUICIDE_PREVENTION_HOTLINE = "1925"
LIFELINE = "1995"
EMERGENCY_SERVICES = "119"
POLICE = "110"
MENTAL_HEALTH_SUPPORT = "1922"
PROTECTION_HOTLINE = "113"
ANTI_FRAUD = "165"

TTS_SPOKEN_SHORT_CODES = (
    POLICE,
    PROTECTION_HOTLINE,
    EMERGENCY_SERVICES,
    ANTI_FRAUD,
    MENTAL_HEALTH_SUPPORT,
    SUICIDE_PREVENTION_HOTLINE,
    LIFELINE,
)
